# Generated by Django 3.2 on 2021-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Created',
            fields=[
                ('Name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100000000)),
                ('Location', models.CharField(max_length=100000000)),
                ('Price', models.IntegerField(default=0)),
                ('Subsequent_Price', models.IntegerField(default=0)),
            ],
        ),
    ]
