# Generated by Django 3.2 on 2021-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_Created', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='created',
            name='No',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='created',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
