# Generated by Django 3.2 on 2021-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_Created', '0002_auto_20210529_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='created',
            name='Agent',
            field=models.CharField(default='Agent', max_length=10000),
        ),
    ]
